# Generated by Django 5.0.1 on 2026-02-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('mp', 'Mercado Pago'), ('other', 'Otro')], max_length=20, verbose_name='Método de pago')),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del turno')),
                ('consumptions_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de consumos')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cierre')),
            ],
            options={
                'verbose_name': 'Cierre de Turno',
                'verbose_name_plural': 'Cierres de Turnos',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('status', models.CharField(choices=[('available', 'Libre'), ('reserved', 'Reservado'), ('cancelled', 'Cancelado'), ('completed', 'Jugado')], default='available', max_length=20, verbose_name='Estado')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono del cliente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courts.court', verbose_name='Cancha')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
