# Generated by Django 5.0.1 on 2026-02-05 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='bookingclosure',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='bookings.booking', verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='bookingclosure',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_made', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['court', 'date', 'start_time'], name='bookings_bo_court_i_3df8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'status'], name='bookings_bo_date_d1c66f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('court', 'date', 'start_time')},
        ),
    ]
