# Generated by Django 5.0.1 on 2026-02-09 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del cliente'),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin',
            field=models.CharField(choices=[('admin', 'Panel Admin'), ('public', 'Reserva Online')], default='admin', max_length=20, verbose_name='Origen de reserva'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.CreateModel(
            name='CancellationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Token de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_token', to='bookings.booking', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Token de Cancelación',
                'verbose_name_plural': 'Tokens de Cancelación',
            },
        ),
    ]
