# Generated by Django 5.0.1 on 2026-02-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_email_booking_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingclosure',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='bookingclosure',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto en efectivo'),
        ),
        migrations.AddField(
            model_name='bookingclosure',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto en transferencia'),
        ),
    ]
