# Generated by Django 5.0.1 on 2026-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default='08:00', verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(default='23:00', verbose_name='Hora de cierre')),
                ('slot_duration_minutes', models.IntegerField(default=90, verbose_name='Duración del turno (minutos)')),
                ('min_cancellation_hours', models.IntegerField(default=2, verbose_name='Horas mínimas para cancelar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Configuración activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Horarios',
                'verbose_name_plural': 'Configuraciones de Horarios',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por turno'),
        ),
    ]
